### ISSUE TITLE
ToDo sensor not supported

### ISSUE THREAD

**Issue by sdholden28** [fixtse/o365-card#5]
It seems the new sensor type "ToDo" is not supported. The O365 integration creates todo.xxx sensors for each task list and I am unable to select this sensor when trying to use the O365 card for tasks. You cannot select the proper entity at all from the UI (I assume due to entity filters) and when you manually specify it via code, you receive the error below.

![image](https://github.com/fixtse/o365-card/assets/97199106/97518863-17ce-4e04-a77a-95f4fcf1a49d)

**Comment by fixtse** [comment]
Hi, sorry for the delay, I've been working on/off on this for too long now, I really wanted to make it work,
but today (while I was working on this) I realized that there is already a to-do card for the new to-do objects, with many of the missing features from mine, and it's already built-in into Home Assistant. (type: todo-list)
So I'll be dropping support for tasks altogether on this card, I'll update the readme to reflect this.

**Comment by amroncz** [comment]
> Hi, sorry for the delay, I've been working on/off on this for too long now, I really wanted to make it work, but today (while I was working on this) I realized that there is already a to-do card for the new to-do objects, with many of the missing features from mine, and it's already built-in into Home Assistant. (type: todo-list) So I'll be dropping support for tasks altogether on this card, I'll update the readme to reflect this.

The official Home Asistant to do list only supports Todoist and Google, but not Microsoft To do, or am I wrong?

**Comment by fixtse** [comment]
It supports all todo.* sensors
Since the o365 integration now provides todo.* sensors instead of the previous sensor.*
They are supported by the card out of the box

**Comment by amroncz** [comment]
> It supports all todo.* sensors Since the o365 integration now provides todo.* sensors instead of the previous sensor.* They are supported by the card out of the box

I see. Thank you very much for your quick feedback. I'll have a look at it.

**Comment by sdholden28** [comment]
Understood. Thank you!
